
import { Project, Experience, SocialLink, Client, SkillCategory } from './types';

// THIS FILE IS AUTOMATICALLY GENERATED BY THE CMS
// DO NOT EDIT MANUALLY IF YOU PLAN TO USE THE CMS AGAIN

export const PROJECTS: Project[] = [
  {
    "id": "fintech-dashboard-2024",
    "title": "Stadium Suite App ",
    "client": "Baltimore Ravens ",
    "roles": [
      "UI Designer"
    ],
    "description": "",
    "year": 2024,
    "heroImage": "https://raw.githubusercontent.com/anikmukhi8designer/AnikMukhiportfolio/main/public/uploads/1764437123505-SSOTechnologyBackgroundIT1.png",
    "thumb": "https://raw.githubusercontent.com/anikmukhi8designer/AnikMukhiportfolio/main/public/uploads/1764437123505-SSOTechnologyBackgroundIT1.png",
    "tags": [
      "Fintech",
      "SaaS",
      "Dashboard"
    ],
    "link": "#",
    "published": true,
    "content": [
      {
        "id": "1",
        "type": "h1",
        "content": "Overview "
      },
      {
        "id": "2",
        "type": "paragraph",
        "content": "The Baltimore Ravens wanted to elevate their VIP suite experience inside the stadium by introducing a smart tablet interface. This tablet would act as the central control system for guests — allowing them to manage entertainment, order food, request services, and enjoy a seamless premium experience during the game."
      },
      {
        "id": "4",
        "type": "h2",
        "content": "Project Goal"
      },
      {
        "id": "5",
        "type": "paragraph",
        "content": "Create a simple, luxurious, and intuitive tablet app that empowers guests to control everything inside their suite without needing staff intervention — enhancing speed, comfort, and overall hospitality."
      },
      {
        "id": "7",
        "type": "quote",
        "content": "The new dashboard has completely transformed how our users interact with their finances."
      },
      {
        "id": "block-1764437431903",
        "type": "h1",
        "content": "Problem statment"
      },
      {
        "id": "block-1764437457419",
        "type": "paragraph",
        "content": "Premium suite guests often rely on attendants for simple actions such as:\n\nAdjusting the TV\n\nOrdering snacks or beverages\n\nRequesting valet\n\nAsking for assistance\n\nThis leads to:\n\nSlower service\n\nInterrupted game experience\n\nHigher staff load\n\nThe Ravens wanted a unified digital interface that gives control back to the guest."
      },
      {
        "id": "block-1764437472528",
        "type": "h1",
        "content": "Solution"
      },
      {
        "id": "block-1764437517138",
        "type": "paragraph",
        "content": "A centralized tablet experience that allows guests to:\n\n🎬 TV & Entertainment Control\n\nLive game broadcast\n\nHighlights & replays\n\nMovies, news, and OTT content\n\nVolume, channel, and input control\n\n🍔 Food & Beverage Ordering\n\nBrowse curated menus\n\nAdd to cart and customize\n\nTrack order status\n\n🚗 Valet Parking Request\n\nRequest car delivery\n\nNotify valet upon arrival\n\n🛍️ Merchandise Shopping\n\nBrowse exclusive Ravens gear\n\nOrder directly to suite\n\n🧑‍💼 One-Tap Service Assistance\n\nNotify staff instantly\n\nTrack service status\n\nAll wrapped inside a clean, modern, stadium-themed UI."
      },
      {
        "id": "block-1764437527045",
        "type": "image",
        "content": "https://raw.githubusercontent.com/anikmukhi8designer/AnikMukhiportfolio/main/public/uploads/1764437541325-Home.png",
        "caption": ""
      },
      {
        "id": "block-1764437566682",
        "type": "image",
        "content": "https://raw.githubusercontent.com/anikmukhi8designer/AnikMukhiportfolio/main/public/uploads/1764437576376-HallOfframe.png",
        "caption": ""
      }
    ]
  }
];

export const EXPERIENCE: Experience[] = [
  {
    "id": "exp-1764437840508",
    "role": "UI/UX Designer Intern",
    "company": "HelpyMoto ",
    "period": "Sept 2023- Jan 2024",
    "description": "Description of responsibilities...",
    "published": false
  },
  {
    "id": "senior-pd-2023",
    "role": "Junior UI/UX Designer ",
    "company": "MobileFirst Applications",
    "period": "Jan 2025- Present ",
    "description": "Leading the design system team and overseeing core product UX.",
    "published": true
  },
  {
    "id": "pd-2021",
    "role": "UI/UX Designer Intern",
    "company": "MobileFirst Applications",
    "period": "Aug 2024- Jan 2025",
    "description": "Worked on various client projects ranging from fintech to healthcare.",
    "published": true
  },
  {
    "id": "freelance-2019",
    "role": "UI/UX Designer ",
    "company": "Freelance Project ",
    "period": "Jan 2024 - Aug 2024",
    "description": "Partnered with early-stage startups to define their MVP visuals.",
    "published": true
  }
];

export const CLIENTS: Client[] = [
  {
    "id": "c1",
    "name": "Nova Inc."
  },
  {
    "id": "c2",
    "name": "Lumina Fashion"
  },
  {
    "id": "c3",
    "name": "Syntax Labs"
  },
  {
    "id": "c4",
    "name": "Pulse Health"
  },
  {
    "id": "c5",
    "name": "Urban Architects"
  },
  {
    "id": "c6",
    "name": "TechFlow"
  },
  {
    "id": "c7",
    "name": "Studio X"
  },
  {
    "id": "c8",
    "name": "Google"
  },
  {
    "id": "c9",
    "name": "Airbnb"
  },
  {
    "id": "c10",
    "name": "Stripe"
  },
  {
    "id": "c11",
    "name": "Linear"
  },
  {
    "id": "c12",
    "name": "Vercel"
  }
];

export const SKILLS: SkillCategory[] = [
  {
    "id": "s1",
    "title": "Design",
    "items": [
      {
        "name": "Figma",
        "icon": "Default"
      },
      {
        "name": "Adobe CC",
        "icon": "Default"
      },
      {
        "name": "Prototyping",
        "icon": "Default"
      },
      {
        "name": "Design Systems",
        "icon": "Default"
      },
      {
        "name": "UI/UX",
        "icon": "Default"
      },
      {
        "name": "Motion",
        "icon": "Default"
      },
      {
        "name": "Framer ",
        "icon": "Framer"
      }
    ]
  },
  {
    "id": "s3",
    "title": "Tools",
    "items": [
      {
        "name": "Linear",
        "icon": "Default"
      },
      {
        "name": "Notion",
        "icon": "Default"
      },
      {
        "name": "VS Code",
        "icon": "Default"
      },
      {
        "name": "Raycast",
        "icon": "Default"
      },
      {
        "name": "Arc",
        "icon": "Default"
      },
      {
        "name": "Spline",
        "icon": "Default"
      }
    ]
  }
];

export const SOCIALS: SocialLink[] = [
  {
    "platform": "Twitter",
    "url": "https://twitter.com",
    "label": "@mukhi_anik"
  },
  {
    "platform": "LinkedIn",
    "url": "https://linkedin.com",
    "label": "Mukhi Anik"
  },
  {
    "platform": "Email",
    "url": "mailto:hello@example.com",
    "label": "hello@mukhianik.com"
  }
];
