import React, { useState, useEffect } from 'react';
import { LayoutDashboard, Briefcase, LogOut, Settings, X, Github, AlertCircle, Wrench, Users } from 'lucide-react';
import WorkTable from './WorkTable';
import ExperienceTable from './ExperienceTable';
import SkillsTable from './SkillsTable';
import ClientsTable from './ClientsTable';
import { useData } from '../../contexts/DataContext';
import { SOCIALS } from '../../data';

// Manually define Vite env types since vite/client is missing
declare global {
  interface ImportMetaEnv {
    VITE_GITHUB_OWNER?: string;
    VITE_GITHUB_REPO?: string;
    VITE_GITHUB_TOKEN?: string;
  }
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}

interface DashboardProps {
  onLogout: () => void;
  onEditProject: (projectId: string) => void;
}

const Dashboard: React.FC<DashboardProps> = ({ onLogout, onEditProject }) => {
  const [activeTab, setActiveTab] = useState<'work' | 'experience' | 'skills' | 'clients'>('work');
  const { projects, experience, clients, skills, resetData } = useData();
  const [isPublishing, setIsPublishing] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  
  // Auth & Config State
  const [cmsCreds, setCmsCreds] = useState({ email: '', password: '' });
  
  const env = (import.meta.env || {}) as any;

  // Initialize Git Config with Env Vars if available
  const [gitConfig, setGitConfig] = useState({ 
    owner: env.VITE_GITHUB_OWNER || '', 
    repo: env.VITE_GITHUB_REPO || '', 
    token: env.VITE_GITHUB_TOKEN || '' 
  });

  useEffect(() => {
    // Load existing settings from LocalStorage
    // Note: LocalStorage will override Env Vars if it exists, allowing UI overrides
    const storedCreds = localStorage.getItem('cms_credentials');
    if (storedCreds) setCmsCreds(JSON.parse(storedCreds));

    const storedGit = localStorage.getItem('cms_git_config');
    if (storedGit) {
        setGitConfig(JSON.parse(storedGit));
    }
  }, []);

  // Helper to encode string to Base64 safely with Unicode support
  const utf8_to_b64 = (str: string) => {
    return window.btoa(unescape(encodeURIComponent(str)));
  };

  const handlePublish = async () => {
    if (!gitConfig.token || !gitConfig.owner || !gitConfig.repo) {
        alert("Please configure your GitHub Repository details in Settings first.");
        setShowSettings(true);
        return;
    }

    setIsPublishing(true);

    try {
        // 1. Generate the content for data.ts
        // We include LAST_UPDATED so that the public site can detect a new version and invalidate cache
        const fileContent = `
import { Project, Experience, SocialLink, Client, SkillCategory } from './types';

// THIS FILE IS AUTOMATICALLY GENERATED BY THE CMS
// DO NOT EDIT MANUALLY IF YOU PLAN TO USE THE CMS AGAIN

export const LAST_UPDATED = "${new Date().toISOString()}";

export const PROJECTS: Project[] = ${JSON.stringify(projects, null, 2)};

export const EXPERIENCE: Experience[] = ${JSON.stringify(experience, null, 2)};

export const CLIENTS: Client[] = ${JSON.stringify(clients, null, 2)};

export const SKILLS: SkillCategory[] = ${JSON.stringify(skills, null, 2)};

export const SOCIALS: SocialLink[] = ${JSON.stringify(SOCIALS, null, 2)};
`;

        const path = 'data.ts';
        const apiUrl = `https://api.github.com/repos/${gitConfig.owner}/${gitConfig.repo}/contents/${path}`;

        // 2. Get current SHA of the file (required for update)
        const getResponse = await fetch(apiUrl, {
            headers: {
                'Authorization': `token ${gitConfig.token}`,
                'Accept': 'application/vnd.github.v3+json'
            }
        });

        if (!getResponse.ok) {
            // If file doesn't exist, we can't update it easily without SHA, but usually it exists.
            // If 404, we might be creating it. GitHub allows create without SHA.
            if (getResponse.status !== 404) {
                 throw new Error(`Failed to fetch current file info (Status: ${getResponse.status})`);
            }
        }

        const getData = getResponse.ok ? await getResponse.json() : null;
        const sha = getData ? getData.sha : undefined;

        // 3. Push the update
        const putResponse = await fetch(apiUrl, {
            method: 'PUT',
            headers: {
                'Authorization': `token ${gitConfig.token}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                message: `CMS Update: ${new Date().toLocaleString()}`,
                content: utf8_to_b64(fileContent),
                sha: sha
            })
        });

        if (!putResponse.ok) {
            const errorData = await putResponse.json();
            throw new Error(`GitHub Error: ${errorData.message}`);
        }

        alert("Successfully committed to GitHub! Vercel should start rebuilding your site now. It may take 1-2 minutes for changes to appear.");

    } catch (error: any) {
        console.error(error);
        alert(`Publishing Failed: ${error.message}`);
    } finally {
        setIsPublishing(false);
    }
  };

  const handleSaveSettings = (e: React.FormEvent) => {
    e.preventDefault();
    localStorage.setItem('cms_credentials', JSON.stringify(cmsCreds));
    localStorage.setItem('cms_git_config', JSON.stringify(gitConfig));
    alert('Settings saved successfully.');
    setShowSettings(false);
  };

  return (
    <div className="min-h-screen bg-neutral-100 flex flex-col">
      {/* CMS Header */}
      <header className="bg-white border-b border-neutral-200 sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-4 md:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <span className="font-bold text-neutral-900 text-lg">New Genre CMS</span>
            <div className="h-4 w-px bg-neutral-300"></div>
            <span className="text-sm text-neutral-500 font-medium">Administrator</span>
          </div>
          
          <div className="flex items-center gap-4">
            <button 
                onClick={handlePublish}
                disabled={isPublishing}
                className={`flex items-center gap-2 px-4 py-2 text-white text-sm font-bold rounded-lg transition-colors disabled:opacity-50 ${
                    !gitConfig.token ? 'bg-neutral-400' : 'bg-green-600 hover:bg-green-700'
                }`}
            >
                {isPublishing ? 'Pushing to GitHub...' : (
                    <>
                        {gitConfig.token ? <Github className="w-4 h-4" /> : <AlertCircle className="w-4 h-4"/>} 
                        {gitConfig.token ? 'Publish Changes' : 'Setup GitHub'}
                    </>
                )}
            </button>
            <button 
                onClick={() => setShowSettings(true)}
                className="p-2 text-neutral-400 hover:text-neutral-900 transition-colors"
                title="Settings"
            >
                <Settings className="w-5 h-5" />
            </button>
            <button onClick={onLogout} className="p-2 text-neutral-400 hover:text-neutral-900 transition-colors" title="Logout">
                <LogOut className="w-5 h-5" />
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-grow p-4 md:p-8 max-w-7xl mx-auto w-full">
        {/* Tabs */}
        <div className="flex flex-wrap gap-1 mb-8 bg-neutral-200/50 p-1 rounded-xl w-fit">
            <button 
                onClick={() => setActiveTab('work')}
                className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                    activeTab === 'work' 
                    ? 'bg-white text-neutral-900 shadow-sm' 
                    : 'text-neutral-500 hover:text-neutral-900'
                }`}
            >
                <LayoutDashboard className="w-4 h-4" /> Projects
            </button>
            <button 
                onClick={() => setActiveTab('experience')}
                className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                    activeTab === 'experience' 
                    ? 'bg-white text-neutral-900 shadow-sm' 
                    : 'text-neutral-500 hover:text-neutral-900'
                }`}
            >
                <Briefcase className="w-4 h-4" /> Experience
            </button>
            <button 
                onClick={() => setActiveTab('skills')}
                className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                    activeTab === 'skills' 
                    ? 'bg-white text-neutral-900 shadow-sm' 
                    : 'text-neutral-500 hover:text-neutral-900'
                }`}
            >
                <Wrench className="w-4 h-4" /> Skills
            </button>
            <button 
                onClick={() => setActiveTab('clients')}
                className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                    activeTab === 'clients' 
                    ? 'bg-white text-neutral-900 shadow-sm' 
                    : 'text-neutral-500 hover:text-neutral-900'
                }`}
            >
                <Users className="w-4 h-4" /> Clients
            </button>
        </div>

        {/* Tab Content */}
        {activeTab === 'work' && <WorkTable onEdit={onEditProject} />}
        {activeTab === 'experience' && <ExperienceTable />}
        {activeTab === 'skills' && <SkillsTable />}
        {activeTab === 'clients' && <ClientsTable />}

        {/* Footer Actions */}
        <div className="mt-12 pt-8 border-t border-neutral-200 flex justify-between items-center text-sm text-neutral-500">
            <p>Changes are saved locally. Click "Publish" to push to GitHub.</p>
            <button onClick={resetData} className="text-red-500 hover:text-red-700 underline">
                Reset to Demo Data
            </button>
        </div>
      </main>

      {/* Settings Modal */}
      {showSettings && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 overflow-y-auto">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in duration-200 my-8">
                <div className="flex justify-between items-center p-6 border-b border-neutral-100">
                    <h3 className="text-lg font-bold text-neutral-900">CMS Configuration</h3>
                    <button onClick={() => setShowSettings(false)}><X className="w-5 h-5 text-neutral-400 hover:text-neutral-900"/></button>
                </div>
                
                <form onSubmit={handleSaveSettings} className="p-6 space-y-6">
                    
                    {/* CMS Access Section */}
                    <div className="space-y-4">
                        <h4 className="text-sm font-bold uppercase tracking-widest text-neutral-500 border-b border-neutral-100 pb-2">CMS Login</h4>
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-xs font-bold text-neutral-900 mb-2">Email</label>
                                <input 
                                    type="email" 
                                    value={cmsCreds.email}
                                    onChange={e => setCmsCreds({...cmsCreds, email: e.target.value})}
                                    className="w-full px-3 py-2 bg-neutral-50 border border-neutral-200 rounded-lg text-sm focus:ring-2 focus:ring-neutral-900 focus:outline-none"
                                    placeholder="admin@example.com"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-neutral-900 mb-2">Password</label>
                                <input 
                                    type="password" 
                                    value={cmsCreds.password}
                                    onChange={e => setCmsCreds({...cmsCreds, password: e.target.value})}
                                    className="w-full px-3 py-2 bg-neutral-50 border border-neutral-200 rounded-lg text-sm focus:ring-2 focus:ring-neutral-900 focus:outline-none"
                                    placeholder="••••••••"
                                />
                            </div>
                        </div>
                    </div>

                    {/* GitHub Connection Section */}
                    <div className="space-y-4">
                        <div className="flex justify-between items-center border-b border-neutral-100 pb-2">
                             <h4 className="text-sm font-bold uppercase tracking-widest text-neutral-500">GitHub Connection</h4>
                             <a href="https://github.com/settings/tokens" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:underline">Get Token (Classic)</a>
                        </div>
                        
                        <div className="p-3 bg-blue-50 text-blue-800 text-xs rounded-lg">
                            <p className="font-bold mb-1">How to connect:</p>
                            <p>1. Use the form below OR create a <code className="bg-blue-100 px-1 rounded">.env</code> file.</p>
                            <p>2. Variables: <code className="bg-blue-100 px-1 rounded">VITE_GITHUB_OWNER</code>, <code className="bg-blue-100 px-1 rounded">VITE_GITHUB_REPO</code>, <code className="bg-blue-100 px-1 rounded">VITE_GITHUB_TOKEN</code>.</p>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-xs font-bold text-neutral-900 mb-2">GitHub Username</label>
                                <input 
                                    type="text" 
                                    required
                                    value={gitConfig.owner}
                                    onChange={e => setGitConfig({...gitConfig, owner: e.target.value})}
                                    className="w-full px-3 py-2 bg-neutral-50 border border-neutral-200 rounded-lg text-sm focus:ring-2 focus:ring-neutral-900 focus:outline-none"
                                    placeholder="e.g. mukhi-anik"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-neutral-900 mb-2">Repository Name</label>
                                <input 
                                    type="text" 
                                    required
                                    value={gitConfig.repo}
                                    onChange={e => setGitConfig({...gitConfig, repo: e.target.value})}
                                    className="w-full px-3 py-2 bg-neutral-50 border border-neutral-200 rounded-lg text-sm focus:ring-2 focus:ring-neutral-900 focus:outline-none"
                                    placeholder="e.g. portfolio-v1"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-neutral-900 mb-2">Personal Access Token</label>
                            <input 
                                type="password" 
                                required
                                value={gitConfig.token}
                                onChange={e => setGitConfig({...gitConfig, token: e.target.value})}
                                className="w-full px-3 py-2 bg-neutral-50 border border-neutral-200 rounded-lg text-sm focus:ring-2 focus:ring-neutral-900 focus:outline-none"
                                placeholder="ghp_xxxxxxxxxxxx"
                            />
                            <p className="text-[10px] text-neutral-400 mt-1">Token is masked. Env vars are supported.</p>
                        </div>
                    </div>

                    <div className="pt-4">
                        <button type="submit" className="w-full py-3 bg-neutral-900 text-white font-bold rounded-lg hover:bg-neutral-800 transition-colors">
                            Save Settings
                        </button>
                    </div>
                </form>
            </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;